# Generated by Django 3.0.3 on 2021-04-15 10:21

import crossword.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crossword', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=crossword.models.default_number)),
                ('pub_date', models.DateTimeField(default=crossword.models.default_pub_date, verbose_name='publication date')),
                ('size', models.IntegerField(default=15, editable=False)),
                ('type', models.IntegerField(choices=[(0, 'Blocked'), (1, 'Barred')], default=0, editable=False)),
                ('instructions', models.TextField(blank=True, editable=False, null=True)),
                ('comments', models.TextField(blank=True)),
                ('user', models.ForeignKey(default=crossword.models.default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'number')},
            },
        ),
    ]
