# Generated by Django 3.0.3 on 2021-04-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0002_puzzle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=30)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('down', models.BooleanField(choices=[(True, 'Down'), (False, 'Across')], default=False, verbose_name='direction')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossword.Puzzle')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
