# Generated by Django 3.0.3 on 2021-04-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0003_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
