# Generated by Django 3.0.3 on 2021-04-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0004_entry_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PuzzleCrossword',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='name',
            field=models.CharField(default='Puzzle Name', max_length=64),
        ),
    ]
