# Generated by Django 3.0.3 on 2021-04-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0005_auto_20210422_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='position',
            new_name='number',
        ),
    ]
