# Generated by Django 3.0.3 on 2021-04-28 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0006_auto_20210424_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=15, editable=False)),
                ('display_order', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossword.Blank')),
            ],
        ),
    ]
